"""Parallel review scraper for product CSVs generated by the product batch run."""

from __future__ import annotations

import argparse
import csv
import datetime as dt
import json
import sys
import time
import zipfile
from collections import defaultdict
from concurrent.futures import ProcessPoolExecutor, as_completed
from dataclasses import asdict, dataclass
from pathlib import Path
from typing import Iterable

from bs4 import BeautifulSoup

from scraper.batch_product_scraper import slugify
from scraper.review_scraper import (
    _build_review_page_url,
    _extract_reviews_from_page,
    get_reviews_url,
)
from scraper.utils import create_browser_context, get_page_html

DEFAULT_MAX_REVIEWS_PER_PRODUCT = 100
DEFAULT_CONCURRENCY = 16
DEFAULT_RETRIES = 2
DEFAULT_REVIEW_WAIT_SECONDS = 5.0
RETRY_REVIEW_WAIT_SECONDS = 8.0
DEFAULT_PAGE_DELAY_SECONDS = 0.0
DEFAULT_PRODUCT_DELAY_SECONDS = 0.0
REVIEWS_PER_PAGE_GUESS = 10
PRODUCT_INPUT_FIELDS = {
    "category",
    "subcategory",
    "title",
    "price",
    "rating",
    "ratings_count",
    "reviews_count",
    "product_url",
    "product_id",
    "source_url",
}
REVIEW_FIELDS = [
    "category",
    "subcategory",
    "product_title",
    "product_price",
    "product_listing_rating",
    "product_ratings_count",
    "product_reviews_count",
    "product_url",
    "product_id",
    "source_url",
    "review_rating",
    "review_title",
    "review_body",
    "reviewer",
    "review_date",
    "helpful_count",
    "variant",
    "city",
    "reviewer_badge",
]
PRODUCT_RESULT_FIELDS = [
    "category",
    "subcategory",
    "product_title",
    "product_url",
    "product_id",
    "status",
    "review_count",
    "error",
]
STATUS_TERMINAL_STATES = {"success", "empty", "failed"}


@dataclass(frozen=True)
class ProductInput:
    """A product row loaded from the product scrape CSVs."""

    category: str
    subcategory: str
    product_title: str
    product_price: str
    product_listing_rating: str
    product_ratings_count: str
    product_reviews_count: str
    product_url: str
    product_id: str
    source_url: str
    source_csv: str


@dataclass(frozen=True)
class ReviewRow:
    """A normalized review row enriched with source product metadata."""

    category: str
    subcategory: str
    product_title: str
    product_price: str
    product_listing_rating: str
    product_ratings_count: str
    product_reviews_count: str
    product_url: str
    product_id: str
    source_url: str
    review_rating: str
    review_title: str
    review_body: str
    reviewer: str
    review_date: str
    helpful_count: str
    variant: str
    city: str
    reviewer_badge: str


@dataclass(frozen=True)
class ProductReviewResult:
    """Summary of one product review scrape attempt."""

    product: ProductInput
    status: str
    review_count: int
    error: str


@dataclass(frozen=True)
class ProductScrapePayload:
    """Rows and status returned by a worker for one product."""

    rows: list[ReviewRow]
    result: ProductReviewResult


def utc_now() -> dt.datetime:
    """Return the current UTC time."""

    return dt.datetime.now(dt.UTC)


def format_elapsed_seconds(total_seconds: float) -> str:
    """Format elapsed seconds as a stable day-hour-minute-second string."""

    elapsed = max(0, int(total_seconds))
    days, remainder = divmod(elapsed, 86400)
    hours, remainder = divmod(remainder, 3600)
    minutes, seconds = divmod(remainder, 60)
    if days > 0:
        return f"{days}d {hours:02d}:{minutes:02d}:{seconds:02d}"
    return f"{hours:02d}:{minutes:02d}:{seconds:02d}"


def log_progress(message: str, start_time: dt.datetime | None = None) -> None:
    """Print a timestamped progress message, optionally including elapsed runtime."""

    now = utc_now()
    prefix = f"[{now.strftime('%Y-%m-%d %H:%M:%S UTC')}]"
    if start_time is not None:
        prefix = f"{prefix} [elapsed {format_elapsed_seconds((now - start_time).total_seconds())}]"
    print(f"{prefix} {message}", flush=True)


def product_key(product: ProductInput) -> str:
    """Return a stable key for deduplicating and resuming products."""

    return product.product_id or product.product_url


def load_product_inputs(product_dir: Path) -> list[ProductInput]:
    """Load product inputs from all product CSV files in a directory."""

    products: list[ProductInput] = []

    for csv_path in sorted(product_dir.glob("*.csv")):
        with csv_path.open(newline="", encoding="utf-8") as csv_file:
            reader = csv.DictReader(csv_file)

            if reader.fieldnames is None or not PRODUCT_INPUT_FIELDS.issubset(reader.fieldnames):
                continue

            for row in reader:
                product_url = row.get("product_url", "").strip()
                if not product_url:
                    continue

                products.append(
                    ProductInput(
                        category=row.get("category", "").strip(),
                        subcategory=row.get("subcategory", "").strip(),
                        product_title=row.get("title", "").strip(),
                        product_price=row.get("price", "").strip(),
                        product_listing_rating=row.get("rating", "").strip(),
                        product_ratings_count=row.get("ratings_count", "").strip(),
                        product_reviews_count=row.get("reviews_count", "").strip(),
                        product_url=product_url,
                        product_id=row.get("product_id", "").strip(),
                        source_url=row.get("source_url", "").strip(),
                        source_csv=csv_path.name,
                    ),
                )

    return products


def normalize_review_rows(
    product: ProductInput,
    raw_reviews: Iterable[dict[str, object]],
    max_reviews: int,
) -> list[ReviewRow]:
    """Copy product metadata onto raw review records and enforce the review cap."""

    rows: list[ReviewRow] = []

    for raw_review in raw_reviews:
        rows.append(
            ReviewRow(
                category=product.category,
                subcategory=product.subcategory,
                product_title=product.product_title,
                product_price=product.product_price,
                product_listing_rating=product.product_listing_rating,
                product_ratings_count=product.product_ratings_count,
                product_reviews_count=product.product_reviews_count,
                product_url=product.product_url,
                product_id=product.product_id,
                source_url=product.source_url,
                review_rating=str(raw_review.get("rating", "")),
                review_title=str(raw_review.get("title", "")),
                review_body=str(raw_review.get("body", "")),
                reviewer=str(raw_review.get("reviewer", "")),
                review_date=str(raw_review.get("date", "")),
                helpful_count=str(raw_review.get("helpful_count", "")),
                variant=str(raw_review.get("variant", "")),
                city=str(raw_review.get("city", "")),
                reviewer_badge=str(raw_review.get("reviewer_badge", "")),
            ),
        )

        if max_reviews > 0 and len(rows) >= max_reviews:
            break

    return rows


def scrape_product_reviews(
    product: ProductInput,
    max_reviews: int,
    retry_count: int,
    wait_seconds: float = DEFAULT_REVIEW_WAIT_SECONDS,
    empty_retry_wait_seconds: float = RETRY_REVIEW_WAIT_SECONDS,
    page_delay_seconds: float = DEFAULT_PAGE_DELAY_SECONDS,
) -> ProductScrapePayload:
    """Scrape capped reviews for one product and return rows plus status."""

    browser = None
    context = None
    raw_reviews: list[dict[str, object]] = []

    try:
        browser, context = create_browser_context()
        review_page_base_url = get_reviews_url(product.product_url)
        max_pages = (
            None
            if max_reviews <= 0
            else max(1, (max_reviews + REVIEWS_PER_PAGE_GUESS - 1) // REVIEWS_PER_PAGE_GUESS)
        )
        page_number = 1

        while max_pages is None or page_number <= max_pages:
            review_page_url = _build_review_page_url(review_page_base_url, page_number)
            html = None

            for attempt in range(retry_count + 1):
                html = get_page_html(
                    context,
                    review_page_url,
                    wait_seconds=wait_seconds,
                )
                if html is not None:
                    break

                time.sleep(2 + attempt)

            if html is None:
                if raw_reviews:
                    break

                return ProductScrapePayload(
                    rows=[],
                    result=ProductReviewResult(
                        product=product,
                        status="failed",
                        review_count=0,
                        error=f"Could not load review page: {review_page_url}",
                    ),
                )

            page_soup = BeautifulSoup(html, "lxml")
            page_reviews = _extract_reviews_from_page(
                page_soup,
                product.product_url,
                product.product_title,
            )

            if page_number == 1 and not page_reviews:
                retry_html = get_page_html(
                    context,
                    review_page_url,
                    wait_seconds=empty_retry_wait_seconds,
                )
                if retry_html is not None:
                    page_soup = BeautifulSoup(retry_html, "lxml")
                    page_reviews = _extract_reviews_from_page(
                        page_soup,
                        product.product_url,
                        product.product_title,
                    )

            if not page_reviews:
                break

            raw_reviews.extend(page_reviews)
            if max_reviews > 0 and len(raw_reviews) >= max_reviews:
                break

            page_number += 1
            if page_delay_seconds > 0:
                time.sleep(page_delay_seconds)

        rows = normalize_review_rows(product, raw_reviews, max_reviews)
        status = "success" if rows else "empty"
        error = "" if rows else "No reviews parsed from Flipkart review pages."
        return ProductScrapePayload(
            rows=rows,
            result=ProductReviewResult(
                product=product,
                status=status,
                review_count=len(rows),
                error=error,
            ),
        )
    except Exception as exc:
        return ProductScrapePayload(
            rows=[],
            result=ProductReviewResult(
                product=product,
                status="failed",
                review_count=0,
                error=str(exc),
            ),
        )
    finally:
        if context is not None:
            context.close()
        if browser is not None:
            browser.close()


def write_rows(path: Path, fieldnames: list[str], rows: Iterable[dict[str, object]]) -> None:
    """Write dictionaries to CSV with a stable header."""

    path.parent.mkdir(parents=True, exist_ok=True)

    with path.open("w", newline="", encoding="utf-8") as csv_file:
        writer = csv.DictWriter(csv_file, fieldnames=fieldnames)
        writer.writeheader()
        for row in rows:
            writer.writerow(row)


def append_rows(path: Path, fieldnames: list[str], rows: Iterable[dict[str, object]]) -> None:
    """Append dictionaries to a CSV, creating the file with a header if needed."""

    rows_to_write = list(rows)
    if not rows_to_write:
        return

    path.parent.mkdir(parents=True, exist_ok=True)
    file_exists = path.exists() and path.stat().st_size > 0

    with path.open("a", newline="", encoding="utf-8") as csv_file:
        writer = csv.DictWriter(csv_file, fieldnames=fieldnames)
        if not file_exists:
            writer.writeheader()
        for row in rows_to_write:
            writer.writerow(row)


def product_result_to_row(result: ProductReviewResult) -> dict[str, object]:
    """Return a CSV-friendly product result row."""

    return {
        "category": result.product.category,
        "subcategory": result.product.subcategory,
        "product_title": result.product.product_title,
        "product_url": result.product.product_url,
        "product_id": result.product.product_id,
        "status": result.status,
        "review_count": result.review_count,
        "error": result.error,
    }


def load_completed_product_keys(output_dir: Path) -> set[str]:
    """Load completed product keys from a previous status ledger."""

    status_path = output_dir / "product_review_status.csv"
    if not status_path.exists():
        return set()

    completed_keys: set[str] = set()
    with status_path.open(newline="", encoding="utf-8") as csv_file:
        reader = csv.DictReader(csv_file)
        for row in reader:
            status = row.get("status", "").strip().lower()
            if status not in STATUS_TERMINAL_STATES:
                continue
            product_id = row.get("product_id", "").strip()
            product_url = row.get("product_url", "").strip()
            key = product_id or product_url
            if key:
                completed_keys.add(key)

    return completed_keys


def load_existing_review_rows(output_dir: Path) -> list[ReviewRow]:
    """Load previously written review rows from the combined CSV when resuming."""

    combined_csv_path = output_dir / "combined_reviews.csv"
    if not combined_csv_path.exists():
        return []

    rows: list[ReviewRow] = []
    with combined_csv_path.open(newline="", encoding="utf-8") as csv_file:
        reader = csv.DictReader(csv_file)
        for row in reader:
            rows.append(
                ReviewRow(
                    category=row.get("category", "").strip(),
                    subcategory=row.get("subcategory", "").strip(),
                    product_title=row.get("product_title", "").strip(),
                    product_price=row.get("product_price", "").strip(),
                    product_listing_rating=row.get("product_listing_rating", "").strip(),
                    product_ratings_count=row.get("product_ratings_count", "").strip(),
                    product_reviews_count=row.get("product_reviews_count", "").strip(),
                    product_url=row.get("product_url", "").strip(),
                    product_id=row.get("product_id", "").strip(),
                    source_url=row.get("source_url", "").strip(),
                    review_rating=row.get("review_rating", "").strip(),
                    review_title=row.get("review_title", "").strip(),
                    review_body=row.get("review_body", "").strip(),
                    reviewer=row.get("reviewer", "").strip(),
                    review_date=row.get("review_date", "").strip(),
                    helpful_count=row.get("helpful_count", "").strip(),
                    variant=row.get("variant", "").strip(),
                    city=row.get("city", "").strip(),
                    reviewer_badge=row.get("reviewer_badge", "").strip(),
                ),
            )

    return rows


def load_existing_results(output_dir: Path) -> list[ProductReviewResult]:
    """Load previously written product result rows from the status ledger."""

    status_path = output_dir / "product_review_status.csv"
    if not status_path.exists():
        return []

    results: list[ProductReviewResult] = []
    with status_path.open(newline="", encoding="utf-8") as csv_file:
        reader = csv.DictReader(csv_file)
        for row in reader:
            product = ProductInput(
                category=row.get("category", "").strip(),
                subcategory=row.get("subcategory", "").strip(),
                product_title=row.get("product_title", "").strip(),
                product_price="",
                product_listing_rating="",
                product_ratings_count="",
                product_reviews_count="",
                product_url=row.get("product_url", "").strip(),
                product_id=row.get("product_id", "").strip(),
                source_url="",
                source_csv="",
            )
            review_count_raw = row.get("review_count", "").strip()
            results.append(
                ProductReviewResult(
                    product=product,
                    status=row.get("status", "").strip(),
                    review_count=int(review_count_raw or 0),
                    error=row.get("error", "").strip(),
                ),
            )

    return results


def append_product_artifacts(output_dir: Path, payload: ProductScrapePayload) -> None:
    """Persist one completed product immediately for resumable runs."""

    review_dict_rows = [asdict(row) for row in payload.rows]
    if review_dict_rows:
        subcategory_csv = (
            output_dir
            / f"{slugify(payload.result.product.category + '__' + payload.result.product.subcategory)}-reviews.csv"
        )
        append_rows(subcategory_csv, REVIEW_FIELDS, review_dict_rows)
        append_rows(output_dir / "combined_reviews.csv", REVIEW_FIELDS, review_dict_rows)

    result_row = product_result_to_row(payload.result)
    append_rows(output_dir / "product_review_status.csv", PRODUCT_RESULT_FIELDS, [result_row])

    if payload.result.status == "empty":
        append_rows(output_dir / "empty_products.csv", PRODUCT_RESULT_FIELDS, [result_row])
    elif payload.result.status == "failed":
        append_rows(output_dir / "failed_products.csv", PRODUCT_RESULT_FIELDS, [result_row])


def write_review_artifacts(
    output_dir: Path,
    review_rows: list[ReviewRow],
    results: list[ProductReviewResult],
    scrape_config: dict[str, object] | None = None,
) -> Path:
    """Write review CSVs, product status reports, JSON/text reports, and ZIP."""

    output_dir.mkdir(parents=True, exist_ok=True)
    rows_by_subcategory: dict[tuple[str, str], list[ReviewRow]] = defaultdict(list)

    for row in review_rows:
        rows_by_subcategory[(row.category, row.subcategory)].append(row)

    for (category, subcategory), rows in rows_by_subcategory.items():
        csv_path = output_dir / f"{slugify(category + '__' + subcategory)}-reviews.csv"
        write_rows(csv_path, REVIEW_FIELDS, [asdict(row) for row in rows])

    combined_csv_path = output_dir / "combined_reviews.csv"
    write_rows(combined_csv_path, REVIEW_FIELDS, [asdict(row) for row in review_rows])

    empty_results = [result for result in results if result.status == "empty"]
    failed_results = [result for result in results if result.status == "failed"]
    write_rows(
        output_dir / "empty_products.csv",
        PRODUCT_RESULT_FIELDS,
        [product_result_to_row(result) for result in empty_results],
    )
    write_rows(
        output_dir / "failed_products.csv",
        PRODUCT_RESULT_FIELDS,
        [product_result_to_row(result) for result in failed_results],
    )
    write_rows(
        output_dir / "product_review_status.csv",
        PRODUCT_RESULT_FIELDS,
        [product_result_to_row(result) for result in results],
    )

    report = {
        "generated_at": dt.datetime.now(dt.UTC).isoformat(),
        "scrape_config": scrape_config or {},
        "summary": {
            "products_attempted": len(results),
            "products_successful": len(
                [result for result in results if result.status == "success"]
            ),
            "products_empty": len(empty_results),
            "products_failed": len(failed_results),
            "total_reviews_collected": len(review_rows),
        },
        "results": [product_result_to_row(result) for result in results],
    }
    (output_dir / "review_run_report.json").write_text(
        json.dumps(report, indent=2, ensure_ascii=False),
        encoding="utf-8",
    )
    if scrape_config is not None:
        (output_dir / "scrape_config.json").write_text(
            json.dumps(scrape_config, indent=2, ensure_ascii=False),
            encoding="utf-8",
        )
    text_lines = [
        "Flipkart review scrape run report",
        f"Generated at: {report['generated_at']}",
        f"Products attempted: {report['summary']['products_attempted']}",
        f"Products successful: {report['summary']['products_successful']}",
        f"Products empty: {report['summary']['products_empty']}",
        f"Products failed: {report['summary']['products_failed']}",
        f"Total reviews collected: {report['summary']['total_reviews_collected']}",
        "",
    ]
    for result in results:
        text_lines.append(
            f"{result.status.upper()}: {result.product.category} / "
            f"{result.product.subcategory} / {result.product.product_id} "
            f"reviews={result.review_count} error={result.error}",
        )
    (output_dir / "review_run_report.txt").write_text(
        "\n".join(text_lines) + "\n",
        encoding="utf-8",
    )

    zip_path = output_dir / "flipkart_review_csvs.zip"
    with zipfile.ZipFile(zip_path, "w", compression=zipfile.ZIP_DEFLATED) as archive:
        for artifact_path in sorted(output_dir.glob("*.csv")):
            archive.write(artifact_path, arcname=artifact_path.name)
        if scrape_config is not None:
            archive.write(output_dir / "scrape_config.json", arcname="scrape_config.json")
        archive.write(output_dir / "review_run_report.json", arcname="review_run_report.json")
        archive.write(output_dir / "review_run_report.txt", arcname="review_run_report.txt")

    return zip_path


def run_review_batch(
    product_dir: Path,
    output_dir: Path,
    max_reviews: int,
    concurrency: int,
    retry_count: int,
    resume: bool = True,
    wait_seconds: float = DEFAULT_REVIEW_WAIT_SECONDS,
    empty_retry_wait_seconds: float = RETRY_REVIEW_WAIT_SECONDS,
    page_delay_seconds: float = DEFAULT_PAGE_DELAY_SECONDS,
    product_delay_seconds: float = DEFAULT_PRODUCT_DELAY_SECONDS,
) -> tuple[list[ReviewRow], list[ProductReviewResult]]:
    """Run review scraping for every loaded product with bounded parallelism."""

    start_time = utc_now()
    products = load_product_inputs(product_dir)
    output_dir.mkdir(parents=True, exist_ok=True)
    completed_keys = load_completed_product_keys(output_dir) if resume else set()
    pending_products = [product for product in products if product_key(product) not in completed_keys]
    review_rows = load_existing_review_rows(output_dir) if resume else []
    results = load_existing_results(output_dir) if resume else []

    log_progress(
        "Starting review batch: "
        f"total_products={len(products)} "
        f"already_completed={len(completed_keys)} "
        f"pending={len(pending_products)} "
        f"existing_reviews={len(review_rows)} "
        f"concurrency={max(1, min(concurrency, max(1, len(pending_products))))} "
        f"resume={'on' if resume else 'off'} "
        f"max_reviews={'uncapped' if max_reviews <= 0 else max_reviews} "
        f"output_dir={output_dir}",
        start_time=start_time,
    )

    if not pending_products:
        log_progress("No pending products. Resume state is already complete.", start_time=start_time)
        return review_rows, results

    concurrency = max(1, min(concurrency, len(pending_products)))

    try:
        with ProcessPoolExecutor(max_workers=concurrency) as executor:
            future_map = {
                executor.submit(
                    scrape_product_reviews,
                    product,
                    max_reviews,
                    retry_count,
                    wait_seconds,
                    empty_retry_wait_seconds,
                    page_delay_seconds,
                ): product
                for product in pending_products
            }

            total_products = len(products)
            already_completed = len(completed_keys)

            for completed, future in enumerate(as_completed(future_map), start=1):
                product = future_map[future]
                payload = future.result()
                review_rows.extend(payload.rows)
                results.append(payload.result)
                append_product_artifacts(output_dir, payload)
                done_count = already_completed + completed
                remaining_count = total_products - done_count
                log_progress(
                    f"{done_count}/{total_products} status={payload.result.status.upper()} "
                    f"remaining={remaining_count} "
                    f"reviews={payload.result.review_count} "
                    f"product_id={product.product_id or 'NA'} "
                    f"category={product.category} "
                    f"subcategory={product.subcategory} "
                    f"title={product.product_title}",
                    start_time=start_time,
                )
                if product_delay_seconds > 0 and completed < len(pending_products):
                    time.sleep(product_delay_seconds)
    except KeyboardInterrupt:
        log_progress(
            "Interrupted by user. Progress already written to disk; rerun the same command to resume.",
            start_time=start_time,
        )
        raise SystemExit(130)

    log_progress(
        f"Completed review batch: products={len(results)} reviews={len(review_rows)} output_dir={output_dir}",
        start_time=start_time,
    )

    return review_rows, results


def parse_args(argv: list[str] | None = None) -> argparse.Namespace:
    """Parse command-line options for review batch scraping."""

    parser = argparse.ArgumentParser(
        description="Scrape capped Flipkart reviews for generated product CSVs.",
    )
    parser.add_argument("--product-dir", type=Path, required=True)
    parser.add_argument("--output-dir", type=Path, required=True)
    parser.add_argument("--max-reviews", type=int, default=DEFAULT_MAX_REVIEWS_PER_PRODUCT)
    parser.add_argument("--concurrency", type=int, default=DEFAULT_CONCURRENCY)
    parser.add_argument("--retries", type=int, default=DEFAULT_RETRIES)
    parser.add_argument("--wait-seconds", type=float, default=DEFAULT_REVIEW_WAIT_SECONDS)
    parser.add_argument(
        "--empty-retry-wait-seconds",
        type=float,
        default=RETRY_REVIEW_WAIT_SECONDS,
    )
    parser.add_argument("--page-delay-seconds", type=float, default=DEFAULT_PAGE_DELAY_SECONDS)
    parser.add_argument(
        "--product-delay-seconds",
        type=float,
        default=DEFAULT_PRODUCT_DELAY_SECONDS,
    )
    parser.add_argument(
        "--no-resume",
        action="store_true",
        help="Ignore any existing progress files in the output directory and start fresh.",
    )
    return parser.parse_args(argv)


def main(argv: list[str] | None = None) -> int:
    """Run the review batch scraper from the command line."""

    args = parse_args(argv)
    run_start_time = utc_now()
    log_progress(
        "CLI args: "
        f"product_dir={args.product_dir} "
        f"output_dir={args.output_dir} "
        f"concurrency={args.concurrency} "
        f"resume={'off' if args.no_resume else 'on'} "
        f"max_reviews={'uncapped' if args.max_reviews <= 0 else args.max_reviews}",
        start_time=run_start_time,
    )
    review_rows, results = run_review_batch(
        product_dir=args.product_dir,
        output_dir=args.output_dir,
        max_reviews=args.max_reviews,
        concurrency=args.concurrency,
        retry_count=args.retries,
        resume=not args.no_resume,
        wait_seconds=args.wait_seconds,
        empty_retry_wait_seconds=args.empty_retry_wait_seconds,
        page_delay_seconds=args.page_delay_seconds,
        product_delay_seconds=args.product_delay_seconds,
    )
    scrape_config = {
        "product_dir": args.product_dir.as_posix(),
        "output_dir": args.output_dir.as_posix(),
        "max_reviews": args.max_reviews,
        "uncapped": args.max_reviews <= 0,
        "concurrency": args.concurrency,
        "resume": not args.no_resume,
        "retries": args.retries,
        "wait_seconds": args.wait_seconds,
        "empty_retry_wait_seconds": args.empty_retry_wait_seconds,
        "page_delay_seconds": args.page_delay_seconds,
        "product_delay_seconds": args.product_delay_seconds,
        "stopping_rule": "Stop each product when Flipkart returns no parseable review cards.",
    }
    zip_path = write_review_artifacts(args.output_dir, review_rows, results, scrape_config)
    log_progress(f"ZIP written: {zip_path}", start_time=run_start_time)
    return 0


if __name__ == "__main__":
    sys.exit(main())
